FROM nginx:latest

# Installa iptables per le regole firewall
RUN apt-get update && \
    apt-get install -y iptables iproute2 tcpdump && \
    rm -rf /var/lib/apt/lists/*

#Script per applicare le regola all'avvio di nginx
RUN apt-get update && \
    apt-get install -y iptables iproute2 tcpdump && \
    rm -rf /var/lib/apt/lists/*