FROM python:3.10

# Installa tcpdump (e libpcap) per ascoltare la rete
RUN apt-get update && \
    apt-get install -y tcpdump && \
    rm -rf /var/lib/apt/lists/*

# Copia il file requirements.txt dal PC al container e installa le librerie Python
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
